name: complete-checking

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linting
        run: |
          pip install -U pip
          pip install norminette
          norminette $(find src/ -type f \( -iname "*.c" ! -iname "wip_*" \)) includes/ libs/builtins/ libs/libft libs/get_next_line
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile the program
        run: |
          sudo apt-get install -y libreadline-dev
          make
  unit_tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          sudo apt-get install -y libreadline-dev
          make test
  integration_tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests the builtins module against a bash
        run: |
          make test_builtins
